name: Test GitStream

on:
  push:
    branches: [main]

jobs:
  gitstream:
    name: Install and run GitStream
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Install GitStream
        run: go install github.com/qbarrand/gitstream@latest

      - name: Run GitStream
        run: ${HOME}/go/bin/gitstream --upstream-url https://github.com/qbarrand/test-upstream --downstream-since 2022-01-01 -downstream-repo-path ../test-downstream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}